version: "3.8"
services:
  inhouse_bot:
    #To use local dockerile
    build:
      context: .
      dockerfile: ./Dockerfile
    image: inhouse_bot
    restart: always
    environment:
      # The connection string is an SQLAlchemy connection string, does not need a password since it uses sockets
      INHOUSE_BOT_CONNECTION_STRING: postgresql+psycopg2://postgres:@/inhouse_bot

      # You need to put your Discord Bot token here
      INHOUSE_BOT_TOKEN: ⚠ PUT_YOUR_TOKEN_HERE ⚠

      # Those emoji help the bot look good and are defined with discord.py emoji syntax
      INHOUSE_BOT_TOP_EMOJI: '<:TOP:1021910091538104321>'
      INHOUSE_BOT_JGL_EMOJI: '<:JG:1021910144600244277>'
      INHOUSE_BOT_MID_EMOJI: '<:MID:1021910129500749974>'
      INHOUSE_BOT_BOT_EMOJI: '<:BOT:1021910195112255508>'
      INHOUSE_BOT_SUP_EMOJI: '<:SUP:1021910164053438494>'

      INHOUSE_BOT_RIOT_API_KEY: ⚠ PUT_YOUR_API_KEY_HERE ⚠

      # Controls running db upgrade
      RUN_MIGRATIONS: true
    volumes:
      # Socket volume to connect to the database
      - type: volume
        source: dbsocket
        target: /var/run/postgresql
    depends_on:
      - db

  db:
    image: postgres:15.0-alpine
    restart: always
    volumes:
      - type: volume
        source: dbsocket
        target: /var/run/postgresql

      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ⚠ POSTGRES PASSWORD ⚠
      POSTGRES_DB: inhouse_bot
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
    depends_on:
      - db
volumes:
  dbsocket:
  pgdata:
