[tool.mypy]
files = "inhouse_bot/database_orm/tables/*.py"
# remove with sqlalchemy 2.0
plugins = "sqlalchemy.ext.mypy.plugin"
python_version = "3.10"
# strict = "True"
# implicit_reexport = "True"
check_untyped_defs = "True"

[[tool.mypy.overrides]]
module = [
    "uvicorn.*",
    "pyot.*",
    "discord.*",
    "lol_id_tools.*",
    "trueskill.*"
]
ignore_missing_imports = true

[tool.isort]
profile = "black"
