"""tournament

Revision ID: 512409880220
Revises: 54b2441edc64
Create Date: 2022-11-30 13:03:01.962993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '512409880220'
down_revision = '54b2441edc64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_code',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('allowed_summoner_ids', postgresql.ARRAY(sa.String(), dimensions=1), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=False),
    sa.Column('pick_type', sa.String(), nullable=False),
    sa.Column('spectator_type', sa.String(), nullable=False),
    sa.Column('map_type', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('tournament_metadata', sa.String(), nullable=True),
    sa.Column('match_id', sa.String(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_code')
    # ### end Alembic commands ###
