"""Removing player rating table

Revision ID: 52693750d371
Revises: 54b2441edc64
Create Date: 2022-11-29 06:54:51.913721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52693750d371'
down_revision = '54b2441edc64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('blue_team_mmr', sa.BigInteger(), nullable=True))
    op.add_column('game', sa.Column('red_team_mmr', sa.BigInteger(), nullable=True))
    op.drop_column('game', 'blue_expected_winrate')
    op.drop_constraint('game_participant_player_id_player_server_id_role_fkey', 'game_participant', type_='foreignkey')
    op.drop_column('game_participant', 'trueskill_mu')
    op.drop_column('game_participant', 'trueskill_sigma')
    op.drop_table('player_rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_rating',
    sa.Column('player_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('player_server_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('TOP', 'JGL', 'MID', 'BOT', 'SUP', name='role_enum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('trueskill_mu', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('trueskill_sigma', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player_id', 'player_server_id'], ['player.id', 'player.server_id'], name='player_rating_player_id_player_server_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'player_server_id', 'role', name='player_rating_pkey')
    )
    op.add_column('game_participant', sa.Column('trueskill_sigma', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('game_participant', sa.Column('trueskill_mu', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key('game_participant_player_id_player_server_id_role_fkey', 'game_participant', 'player_rating', ['player_id', 'player_server_id', 'role'], ['player_id', 'player_server_id', 'role'])   
    op.add_column('game', sa.Column('blue_expected_winrate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('game', 'red_team_mmr')
    op.drop_column('game', 'blue_team_mmr')
    # ### end Alembic commands ###