"""player-summoner-puuid

Revision ID: 5b643020b8f5
Revises: 6ee9679b5820
Create Date: 2022-10-08 07:30:39.672353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b643020b8f5'
down_revision = '6ee9679b5820'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('summoner_puuid', sa.String(), nullable=True))
    op.create_unique_constraint('unique_server_id_summoner_puuid', 'player', ['server_id', 'summoner_puuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_server_id_summoner_puuid', 'player', type_='unique')
    op.drop_column('player', 'summoner_puuid')
    # ### end Alembic commands ###
