"""game_participant player fk cascade

Revision ID: 6d802e6186fb
Revises: 089ebe529fd3
Create Date: 2022-12-02 11:33:21.094172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d802e6186fb'
down_revision = '089ebe529fd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('game_participant_player_id_player_server_id_fkey', 'game_participant', type_='foreignkey')
    op.create_foreign_key('game_participant_player_id_player_server_id_fkey', 'game_participant', 'player', ['player_id', 'player_server_id'], ['id', 'server_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('game_participant_player_id_player_server_id_fkey', 'game_participant', type_='foreignkey')
    op.create_foreign_key('game_participant_player_id_player_server_id_fkey', 'game_participant', 'player', ['player_id', 'player_server_id'], ['id', 'server_id'])
    # ### end Alembic commands ###
