"""initial

Revision ID: 6ee9679b5820
Revises: 
Create Date: 2022-10-07 23:58:37.986505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee9679b5820'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_information',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('server_id', sa.BigInteger(), nullable=True),
    sa.Column('blue_expected_winrate', sa.Float(), nullable=True),
    sa.Column('winner', sa.Enum('BLUE', 'RED', name='team_enum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'server_id')
    )
    op.create_table('server_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id')
    )
    op.create_table('player_rating',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('player_server_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('TOP', 'JGL', 'MID', 'BOT', 'SUP', name='role_enum'), nullable=False),
    sa.Column('trueskill_mu', sa.Float(), nullable=True),
    sa.Column('trueskill_sigma', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id', 'player_server_id'], ['player.id', 'player.server_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'player_server_id', 'role')
    )
    op.create_table('queue_player',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('TOP', 'JGL', 'MID', 'BOT', 'SUP', name='role_enum'), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('player_server_id', sa.BigInteger(), nullable=True),
    sa.Column('duo_id', sa.BigInteger(), nullable=True),
    sa.Column('queue_time', sa.DateTime(), nullable=True),
    sa.Column('ready_check_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel_information.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id', 'player_server_id'], ['player.id', 'player.server_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id', 'role', 'player_id')
    )
    op.create_index(op.f('ix_queue_player_channel_id'), 'queue_player', ['channel_id'], unique=False)
    op.create_index(op.f('ix_queue_player_player_id'), 'queue_player', ['player_id'], unique=False)
    op.create_table('game_participant',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('BLUE', 'RED', name='team_enum'), nullable=False),
    sa.Column('role', sa.Enum('TOP', 'JGL', 'MID', 'BOT', 'SUP', name='role_enum'), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('player_server_id', sa.BigInteger(), nullable=True),
    sa.Column('champion_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('trueskill_mu', sa.Float(), nullable=True),
    sa.Column('trueskill_sigma', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id', 'player_server_id', 'role'], ['player_rating.player_id', 'player_rating.player_server_id', 'player_rating.role'], ),
    sa.ForeignKeyConstraint(['player_id', 'player_server_id'], ['player.id', 'player.server_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'side', 'role')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_participant')
    op.drop_index(op.f('ix_queue_player_player_id'), table_name='queue_player')
    op.drop_index(op.f('ix_queue_player_channel_id'), table_name='queue_player')
    op.drop_table('queue_player')
    op.drop_table('player_rating')
    op.drop_table('server_config')
    op.drop_table('player')
    op.drop_table('game')
    op.drop_table('channel_information')
    # ### end Alembic commands ###
