"""channel_information_server_id_not_null

Revision ID: 94ea02624e13
Revises: 78ff3b7b3f1e
Create Date: 2022-10-23 03:22:43.621508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ea02624e13'
down_revision = '78ff3b7b3f1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel_information', 'server_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel_information', 'server_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
