name: Build and Push Docker container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -t ghcr.io/classbabacar/msoft_bot/msoft_bot .
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: push to GitHub Container Registry
      run:  docker push ghcr.io/classbabacar/msoft_bot/msoft_bot:latest
