name: Build and Push Docker container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    # Login in to ghcr
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: adamschachne
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Build the image with tag matching repo owner name
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -t ghcr.io/adamschachne/msoft_bot/msoft_bot .
    
      # Upload the image
    - name: push to GitHub Container Registry
      run:  docker push ghcr.io/adamschachne/msoft_bot/msoft_bot:latest
