name: Build and Push Docker container

on:
  push:
    # whenever code is merged to main, deploy new image
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    # Login in to ghcr
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.repository }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Build the image with tag matching repo owner name
    - uses: actions/checkout@v1
    - run: |
        docker build -t ghcr.io/${{ github.repository }} .
        docker tag ghcr.io/${{ github.repository }} ghcr.io/inhouse_bot:latest
        docker push ghcr.io/inhouse_bot:latest  
