name: Continuous Integration

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Black Check
        uses: jpetrucciani/black-check@22.10.0
        with:
          # File or directory to run black on
          path: "inhouse_bot"

      - name: Mypy Check
        uses: jpetrucciani/mypy-check@0.971
        with:
          requirements: sqlalchemy sqlalchemy2-stubs
          mypy_flags: '--config-file pyproject.toml'

      # TODO run unit tests
