name: Run Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Black Check
        uses: jpetrucciani/black-check@22.10.0
        with:
          # File or directory to run black on
          path: "**/*.py"
          # Optional Black flags (refer to `black --help`)
          # black_flags: # optional, default is

      # TODO run unit tests
